### PR TITLE
Added a simple GUI app for playing video

### PR DESCRIPTION
**Pull request by GitHubDragonFly**
### Description

- Added a rather simple GUI app for playing video
- Updated README.md

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or new feature that would cause existing functionality to change)
- [x] Docstrings/Documentation updated
- [ ] New Feature to Caer
- [x] New Examples to [`examples`](https://github.com/jasmcaus/caer/tree/master/examples)
- [ ] New tests added to cover the changes

### Checklist:

- [x] I have followed the [contribution guidelines](CONTRIBUTING.md) and code style for this project.
- [ ] I have added tests covering my contributions (**important**).
- [x] I have updated the documentation accordingly.
- [x] This PR is being made to `dev` and not `master` (**important**).
- [ ] I will squash merge this PR into `dev` (optional)

### CODE REVIEW

**Review by jasmcaus — CHANGES_REQUESTED** [review]
Please update all references of `caer.core.cv.imwrite` to `caer.imwrite`. 
Caer has valid `imsave` and `imwrite` methods.

**Comment by GitHubDragonFly** [comment]
That doesn't work with v1.9.8 since it gives me `module 'caer' has no attribute 'imwrite'`

My tests with `caer.core.cv.imwrite` work properly and save the screenshots.

**Comment by jasmcaus** [comment]
Oops, my bad - I'm a little too groggy. Cart doesn't have an `imwrite` member; its equivalent is `caer.imsave`. Use that instead please

**Comment by jasmcaus** [comment]
LGTM! Thanks for this!

**Review by jasmcaus — APPROVED** [review]

**Comment by GitHubDragonFly** [comment]
Just in case if you might be interested, there is an expanded version of this GUI which I decided to put in my own repository:

https://github.com/GitHubDragonFly/CAER_Video_GUI

**Comment by jasmcaus** [comment]
Okay, that's great! If you'd like to reflect the same here on this repo as well, feel free. No pressure :)
Many thanks for your repeated contributions! They're very well appreciated by me 👍🏻

**Comment by GitHubDragonFly** [comment]
I have updated the README.md to show the link to my repository.

There is now also an additional GUI which allows playing multiple video sources at the same time.

Caer users should be able to use at least some code or ideas from any of the examples.

**Comment by GitHubDragonFly** [comment]
Just to let you know that, in my repository, I have managed to include a code to record and save a camera video to a file.

Interestingly enough, when Edges are enabled the window will show those frames but they just don't get recorded in the file.
This has to be somehow related to the library since all other frames get recorded.

**Comment by jasmcaus** [comment]
I don't think it has anything to do with Caer, since it abstracts over OpenCV's functionality.

**Comment by GitHubDragonFly** [comment]
I agree with you.

My remarks are generally intended to keep you aware of some weird things in case if somebody else complains about those.

In my code, there are 4 effects that use cv directly: caer.core.cv.GaussianBlur, caer.core.cv.Canny (edges) and caer.core.cv.filter2D (sharpen and emboss). I did put a comment about Edges and Emboss not liking to be applied at the same time. Also, the Sharpen effect has a less of an impact on a large size images.

Somebody should eventually let OpenCV people know these things (if they haven't already).

**Comment by GitHubDragonFly** [comment]
Just another FYI, recording frames with Edges effect applied to them works when the image is converted from GREY to BGR.

I will have to experiment a bit more but that was probably the reason for Edges and Emboss dislike.
